/* Test case for non-centrality distribution - for comparison
* with the Java Statistics library
*/
TITLE "Test: Davies Algorithm for CDF of Weighted Sum of non-central Chi-Squares";
%INCLUDE "common.sas";

PROC IML SYMSIZE=2000 WORKSIZE=6000;
RESET SPACES=4;
%INCLUDE "&GLUECK_MULLER_IML_DIRECTORY\BASEPA1.IML"/NOSOURCE2;
%INCLUDE "&GLUECK_MULLER_IML_DIRECTORY\BASEPE1.IML"/NOSOURCE2;
%INCLUDE "&GLUECK_MULLER_IML_DIRECTORY\BASEQ1.IML"/NOSOURCE2;
%INCLUDE "&GLUECK_MULLER_IML_DIRECTORY\POWUA1.IML"/NOSOURCE2;
%INCLUDE "&GLUECK_MULLER_IML_DIRECTORY\POWHA1.IML"/NOSOURCE2;
%INCLUDE "&GLUECK_MULLER_IML_DIRECTORY\QLIB01.IML"/NOSOURCE2;
%INCLUDE "&GLUECK_MULLER_IML_DIRECTORY\BASEU4.IML"/NOSOURCE2;


LAMBDAS = {1,1,1};
OMEGAS = {5,10,1};
DFS = {1,1,1};
QUANTILES = {100};
ACCURACY = 1.2;

do I = 1 to NCOL(QUANTILES);
	Q = QUANTILES[I];
	P = QPROB(Q, LAMBDAS, DFS, OMEGAS, ACCURACY);
	HOLDPROB = HOLDPROB//(Q||P);
end;

NAMES = {"Quantile" "Pr(Q < q)"};
PRINT HOLDPROB[COLNAME=NAMES];



QUIT;
